import { WriteExcel } from "@/functions";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";
import KerryJPEG from "../public/transport/kerry.jpeg";
import ShopeeJPEG from "../public/transport/Shopee.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>ระบบเคลมสินค้า</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Prompt:wght@100;300;400;500;700;800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous"
        />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
          crossorigin="anonymous"
        />
      </Head>
      
      <main className={styles.main}>
        <h1>สร้างไฟล์เคลมสินค้า</h1>
        <br />
        <h2>เลือกชื่อขนส่ง</h2>
        <br />

        <Link href="./Kerry">
        <Image alt="Kerry"  src={KerryJPEG} width={100} height={100} decoding="async" data-nimg={1} loading="lazy" style={{color: 'transparent', borderRadius: 10}} />
        </Link>
        <br/>
        <Link href="./Shopee.js">
        <Image alt="Shopee" src={ShopeeJPEG} width={100} height={100} decoding="async" data-nimg={1} loading="lazy" style={{color: 'transparent', borderRadius: 10}} />
        </Link>
        

        
      </main>
    </>
  );
}
